apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubernetes-component-2
  labels:
    backstage.io/kubernetes-id: my-kubernetes-component-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-kubernetes-component-2
  template:
    metadata:
      labels:
        app: my-kubernetes-component-2
        backstage.io/kubernetes-id: my-kubernetes-component-2
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: 
        - /bin/sh
        args:
        - -c
        - "tail -f /dev/null"
